### ISSUE TITLE
The demo can not work well on chrome canary 58.0.3011.0

### ISSUE THREAD

**Issue by xiuqijix** [intel/websensor-compass#9]
The code of https://sensor-compass.appspot.com/ is old, pls help to update, thanks.
I set up the demo on [https://honry.github.io/demo/tests/websensor-compass/index.html](url)
It can work on chrome canary 58.0.3001.3, but the compass can't rotate and no angle value on chrome canary 58.0.3011.0.
There are some messages on the Console tab.
> [.Offscreen-For-WebGL-0x7633374400]RENDER WARNING: there is no texture bound to the unit 0
> WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by kenchris** [comment]
I will update it, sorry.

The render warning normally comes when you are doing remote debugging. So you have to close the devtools and close the browser

**Comment by kenchris** [comment]
You are right, I also get that error now. Maybe you could debug (I am not very experience with WebGL) or report it to the crbug.com/new

**Comment by kenchris** [comment]
This here is the code resulting in the error

``` 
      // Draw Cap Object

      // Disable texture for cap object
      this.gl.disableVertexAttribArray(this.gl.textureCoordAttribute);

      this.gl.bindBuffer(this.gl.ARRAY_BUFFER, this.mCapVertexBufferGL);
      this.gl.vertexAttribPointer(this.gl.vertexPositionAttribute, this.mCapVertexBufferGL.itemSize, this.gl.FLOAT, false, 0, 0);

      this.gl.bindTexture(this.gl.TEXTURE_2D, null);

      this.gl.bindBuffer(this.gl.ELEMENT_ARRAY_BUFFER, this.mCapIndexBufferGL);

      this.gl.drawElements(this.gl.TRIANGLES, dx * (dy - rh) * 6, this.gl.UNSIGNED_SHORT, 0);
```

Now I don't know why

**Comment by kenchris** [comment]
Removing this line 

```
this.gl.bindTexture(this.gl.TEXTURE_2D, null);
```

makes it stop complaining but the compass isnt moving any longer

**Comment by mkollaro** [comment]
The warning about no texture bound is there because `bindTexture(this.gl.TEXTURE_2D, null)` unbinds the texture. That part of the code draws a black cap on the very bottom of the compass and doesn't require any texture, so the code unbinds it, but the shaders expect a texture to be there and complain. A solution to that would be to either change the shaders when that bottom cap is being drawn, or to create some dummy 1x1 black texture just for that. I can try fixing that.

However, I don't think that warning is related to the issue of the compass not moving. I replaced `this.gamma` with 30 on line 921 `in scripts/compass.js` and it rotated itself by 30 degrees just fine. Tested this on a recent chromium build from git too. I can't debug this problem because I don't have any accelerometer at hand - try setting those values on line 921 manually and see if that works. If yes, then the issue that they don't update properly.

**Comment by kenchris** [comment]
It would be super cool if you could fix this warning! When you get too many of these warnings, Chrome stops drawing

**Comment by kenchris** [comment]
Something like this I guess?

```
      // Initialize textures with empty 1x1 texture while real textures are loaded
      // see: http://stackoverflow.com/a/19748905
      for(var i = 0, l = this.mTextures.length; i < l; i++) {
        this.gl.bindTexture(this.gl.TEXTURE_2D, this.mTextures[i]);
        this.gl.texImage2D(this.gl.TEXTURE_2D, 0, this.gl.RGBA, 1, 1, 0, this.gl.RGBA, this.gl.UNSIGNED_BYTE,
          new Uint8Array([0, 0, 0, 255])); // initialize as black 1x1 texture
        this.gl.bindTexture(this.gl.TEXTURE_2D, null);
      }
```

**Comment by xiuqijix** [comment]
The issue is not reproduce, so close it, thanks.
